- hosts: kubeslave
  tasks:
  - name: copy the join command file
    copy:
      src: "../files/join_command.sh"
      dest: "/root/"
      mode: "+x"
    register: join_command_copied

  
  - name: running kubeadm join command
    command: "bash /root/join_command.sh/{{ groups['kubemaster'][0] }}/join_command.sh"
    
